name: Compile package
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX file
        uses: xu-cheng/texlive-action@v3
        with:
          run: |
            pdflatex brandstyler.dtx
            makeindex -s gind.ist -o brandstyler.ind brandstyler.idx
            makeindex -s gglo.ist -o brandstyler.gls brandstyler.glo
            pdflatex brandstyler.dtx
      - name: Move CTAN files into folder
        run: |
          mkdir -p ctan/brandstyler
          mv brandstyler.dtx ctan/brandstyler/brandstyler.dtx
          mv brandstyler.ins ctan/brandstyler/brandstyler.ins
          mv README.md ctan/brandstyler/README.md
          mv brandstyler.pdf ctan/brandstyler/brandstyler-doc.pdf
      - name: Move sty files into folder
        run: |
          mkdir sty
          mv *.sty sty
      - name: Zip CTAN files
        uses: actions/upload-artifact@v4
        with:
          name: CTAN-files
          path: ctan/
      - name: Zip sty file
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: sty/